FROM nginx:1.19.2-alpine
WORKDIR /etc/nginx

# setup imaged
RUN \
mkdir -p /certs /sites /defaults && \
rm -f /etc/nginx/conf.d/default.conf

# copy the defaults to image
COPY defaults/ /defaults/
COPY defaults/ /

# copy base configs to /etc/nginx
COPY *.conf ./

VOLUME /sites
VOLUME /certs
