name: Docker Build and Push

on: 
  push:
    branches:
    - master
    release:
      types: [published]
    
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Publish Docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: weavc/weavc-nginx/main
          tag_with_ref: true
      - name: Publish ghcr
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: weavc/weavc-nginx
          dockerfile: Dockerfile
          tag_with_ref: true
